### ISSUE TITLE
Cannot find TextureTypeToString in scope AiTextureType.swift

### ISSUE THREAD

**Issue by nasirzeeshan** [ctreffs/SwiftAssimp#11]
### Bug Description

*A clear and concise description of what the bug is.
When i add this this package as package dependencies and try to build my application i got build failure error that reads as
String(cString: TextureTypeToString(aiTextureType(rawValue: rawValue)))
Cannot find TextureTypeToString in scope 
it is in AiTextureType.swift file

### Information

branch master
macOS 12.5 Monterey
swift version 5.6.1

### Checklist

- [ x] If possible, I've reproduced the issue using the `main`/`master` branch of this package.
- [ x] I've searched for existing issues under the issues tab.
- [ x] The bug is reproducible

### Steps to Reproduce

*Steps to reproduce the behavior:*

Add this package as package dependencies and try to build your application

extension AiTextureType: CustomDebugStringConvertible {
    public var debugDescription: String {
        String(cString: TextureTypeToString(aiTextureType(rawValue: rawValue)))
    }
}

### Expected behavior

This should build without any problem

### Actual behavior

i got build failure with above message

**Comment by SimonBenAnderson** [comment]
I changed it to `aiTextureTypeToString` and it built correctly, but ended up with a variety of symbol matching errors. @ctreffs  by any chance do you know if it is working with the latest assimp?

**Comment by jinggooo** [comment]
i have similar error. Maybe symbol matching errors can fix with reinstall assimp or brew link assimp on mac

i have another error on mac m1.
when i fix TextureTypeToString() to aiTextureTypeToString(),
i got      "**dyld[31427]: Library not loaded: /opt/homebrew/opt/assimp/lib/libassimp.5.dylib**"      error.
i tried 
> 1. DYLD_LIBRARY_PATH to new path, 
> 2. permission to file and directory, 
> 3. reinstall assimp, 
> 4. reinstall swiftassimp
> 5. export DYLD_LIBRARY_PATH=/opt/homebrew/opt/assimp/lib:/opt/homebrew/Cellar/assimp/5.2.5/lib:/Users/mymac/Desktop/assimp/lib:/usr/lib/system/introspection added to .zshrc file and source it, and whatever chatGPT said.
> 6. add DYLD_LIBRARY_PATH to xcode
but they weren't work.

is there anybody had seen error like me or solve it
any comments are welcome.
thanks

**Comment by jinggooo** [comment]
I want to convert tinygltf to obj or ply file format in StandardCyborgExample
And i got this too.
**Building for iOS, but linking in dylib file (/opt/homebrew/Cellar/assimp/5.2.5/lib/libassimp.dylib) built for macOS**

**Comment by pressanykeyplease** [comment]
Hey @ctreffs can you help please?

**Comment by ctreffs** [comment]
Should be fixed with #23 and release 2.2.0 - please verify - sorry for taking so long
