### ISSUE TITLE
Hardcoded local path

### ISSUE THREAD

**Issue by joskuijpers** [ctreffs/SwiftAssimp#2]
https://github.com/ctreffs/SwiftAssimp/blob/790098e3afb62467dc855d59fc2b6c72e41c5493/Tests/AssimpTests/AssimpTests.swift#L246

This path is hardcoded and fails the tests for me. I don't know what object it should be pointing to.

**Comment by ctreffs** [comment]
Fixed with https://github.com/ctreffs/SwiftAssimp/releases/tag/1.2.1
