### ISSUE TITLE
Minor README updates

### ISSUE THREAD

**Issue by Winde4th** [ctreffs/SwiftAssimp#4]
Hey @ctreffs thanks for your work here,

I don't have rights to open a PR so I just follow you some minors updates you could merge if you want ;) (see attached patch)

cheers

[minor-readme-updates.patch.zip](https://github.com/ctreffs/SwiftAssimp/files/4586941/minor-readme-updates.patch.zip)

**Comment by ctreffs** [comment]
Thank you @Winde4th for your input. I've updated README.md to make install instructions clearer.
